# Generated by Django 4.2.14 on 2024-07-19 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('current_level', models.IntegerField()),
                ('last_collected', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
